import { UserRole } from '../modules/user/user.constants';
import Actions from './actions';

type Subset = Partial<Actions>;

const allRoles: {
  [key in UserRole]: Subset[];
} = {
  [UserRole.RESIDENT]: [
    Actions.SIGN_OUT,
    Actions.MANAGE_SELF,
    Actions.READ_UNIT,
    Actions.READ_DEFECTS,
    Actions.MANAGE_UNIT,
    Actions.CREATE_DEFECT,
    Actions.CONFIRM_DONE,
    Actions.READ_FAQ,
    Actions.READ_INQUIRY,
    Actions.CREATE_INQUIRY,
    Actions.READ_NOTIFICATION,
    Actions.READ_RESIDENT_COMPLEX,
    Actions.CREATE_INQUIRY,
    Actions.DELETE_UNIT_RESIDENT,
  ],
  [UserRole.CONTRACTOR_ADMIN]: [
    Actions.SIGN_OUT,
    Actions.MANAGE_SELF,
    Actions.DEPLOY_USER,
    Actions.BLOCK_USER,
    Actions.READ_USERS,
    Actions.READ_CONTRACTOR_UNIT,
    Actions.CREATE_CONTRACTOR_UNIT,
    Actions.UPDATE_CONTRACTOR_UNIT,
    Actions.DELETE_CONTRACTOR_UNIT,
    Actions.READ_CONTRACTOR_UNIT_TYPE,
    Actions.CREATE_CONTRACTOR_UNIT_TYPE,
    Actions.UPDATE_CONTRACTOR_UNIT_TYPE,
    Actions.DELETE_CONTRACTOR_UNIT_TYPE,
    Actions.CREATE_WORK,
    Actions.CREATE_COMPLEX,
    Actions.UPDATE_COMPLEX,
    Actions.DELETE_COMPLEX,
    Actions.READ_WORK,
    Actions.READ_PARTNERS,
    Actions.CREATE_PARTNERSHIP,
    Actions.ASSIGN_DUTY,
    Actions.READ_DUTY,
    Actions.DELETE_DUTY,
    Actions.READ_RESIDENTS,
    Actions.READ_DEFECTS,
    Actions.CREATE_INQUIRY,
    Actions.READ_CONTRACTOR_INQUIRY,
    Actions.ANSWER_CONTRACTOR_INQUIRY,
    Actions.READ_CONTRACTOR_DEFECT,
  ],
  [UserRole.CONTRACTOR_SUB_ADMIN]: [Actions.SIGN_OUT, Actions.MANAGE_SELF],
  [UserRole.CONTRACTOR_WORKER]: [Actions.SIGN_OUT, Actions.MANAGE_SELF],
  [UserRole.PARTNER_ADMIN]: [
    Actions.SIGN_OUT,
    Actions.MANAGE_SELF,
    Actions.DEPLOY_USER,
    Actions.READ_DEFECTS,
    Actions.READ_PARTNER_DEFECT,
    Actions.REJECT_DUTY,
    Actions.ASSIGN_TASK,
    Actions.READ_PARTNER_EMPLOYEE,
    Actions.READ_PARTNER_DEFECT,
    Actions.CREATE_INQUIRY,
    Actions.READ_PARTNER_INQUIRY,
    Actions.READ_NOTICE,
    Actions.CREATE_PARTNER_EMPLOYEE,
    Actions.DELETE_PARTNER_EMPLOYEE,
    Actions.UPDATE_PARTNER_EMPLOYEE,
  ],
  [UserRole.PARTNER_SUB_ADMIN]: [Actions.SIGN_OUT, Actions.MANAGE_SELF, Actions.ASSIGN_TASK],
  [UserRole.PARTNER_ENGINEER]: [
    Actions.SIGN_OUT,
    Actions.MANAGE_SELF,
    Actions.READ_UNIT,
    Actions.READ_DEFECTS,
    Actions.READ_TASKS,
    Actions.REPAIR_DONE,
    Actions.REJECT_TASK,
    Actions.READ_COMPLEX,
    Actions.READ_DONG,
    Actions.READ_HO,
  ],
  [UserRole.PSPACE_ADMIN]: [
    Actions.SIGN_OUT,
    Actions.READ_ALL_INQUIRY,
    Actions.MANAGE_SELF,
    Actions.DEPLOY_USER,
    Actions.READ_ALL_USER,
    Actions.DELETE_ALL_USER,
    Actions.READ_ALL_DEFECTS,
    Actions.READ_PSPACE_EMPLOYEE,
    Actions.UPDATE_PSPACE_ROLE,
    Actions.DELETE_PSPACE_EMPLOYEE,
    Actions.UPDATE_PSPACE_EMPLOYEE,
    Actions.UPDATE_ALL_USER,
    Actions.BLACKLIST_ALL_USER,
  ],
  [UserRole.PSPACE_SUB_ADMIN]: [Actions.SIGN_OUT, Actions.MANAGE_SELF],
  [UserRole.PSPACE_WORKER]: [Actions.SIGN_OUT, Actions.MANAGE_SELF],
};

const roleRights: Map<string, string[]> = new Map(Object.entries(allRoles));
export default roleRights;
