export enum UserType {
  RESIDENT = 'RESIDENT',
  CONTRACTOR = 'CONTRACTOR',
  PARTNER = 'PARTNER',
  PSPACE = 'PSPACE',
}

export enum UserRole {
  RESIDENT = 'RESIDENT',
  CONTRACTOR_ADMIN = 'CONTRACTOR_ADMIN',
  CONTRACTOR_SUB_ADMIN = 'CONTRACTOR_SUB_ADMIN',
  CONTRACTOR_WORKER = 'CONTRACTOR_WORKER',
  PARTNER_ADMIN = 'PARTNER_ADMIN',
  PARTNER_SUB_ADMIN = 'PARTNER_SUB_ADMIN',
  PARTNER_ENGINEER = 'PARTNER_ENGINEER',
  PSPACE_ADMIN = 'PSPACE_ADMIN',
  PSPACE_SUB_ADMIN = 'PSPACE_SUB_ADMIN',
  PSPACE_WORKER = 'PSPACE_WORKER',
}

export enum PartnerRole {
  PARTNER_ADMIN = 'PARTNER_ADMIN',
  PARTNER_SUB_ADMIN = 'PARTNER_SUB_ADMIN',
  PARTNER_ENGINEER = 'PARTNER_ENGINEER',
}

export enum ContractorRole {
  CONTRACTOR_ADMIN = 'CONTRACTOR_ADMIN',
  CONTRACTOR_SUB_ADMIN = 'CONTRACTOR_SUB_ADMIN',
  CONTRACTOR_WORKER = 'CONTRACTOR_WORKER',
}

export enum BackofficeLoginUserTypeEnum {
  CONTRACTOR = 'CONTRACTOR',
  PARTNER = 'PARTNER',
  PSPACE = 'PSPACE',
}

export const BackofficeLoginUserTypeArray: string[] = Object.values(BackofficeLoginUserTypeEnum);
